package com.appliedsni.channel.core.server.user.domain;
// Generated 3 Nov, 2018 11:22:10 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * branch generated by hbm2java
 */
@Entity
@Table(name = "xbranch")
public class BranchEntity implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "xcompany", column = @Column(name = "xcompany", nullable = false, length = 20)),
			@AttributeOverride(name = "xidkey", column = @Column(name = "xidkey", nullable = false, length = 20)) })
	private BranchIdEntity mId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xaddedby")
	private UserEntity mUser;

	@Column(name = "xname", length = 200)
	private String mName;

	@Column(name = "xversion", nullable = false)
	private int mVersion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xadded", length = 29)
	private Date mAdded;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xlastupdate", length = 29)
	private Date mLastupdate;

	public BranchEntity() {
	}

	public BranchEntity(BranchIdEntity id, int mversion) {
		this.mId = id;
		this.mVersion = mversion;
	}

	public BranchEntity(BranchIdEntity id, UserEntity muser, String mname, int mversion, Date madded,
			Date mlastupdate) {
		this.mId = id;
		this.mUser = muser;
		this.mName = mname;
		this.mVersion = mversion;
		this.mAdded = madded;
		this.mLastupdate = mlastupdate;
	}

	public BranchIdEntity getId() {
		return mId;
	}

	public void setId(BranchIdEntity pId) {
		mId = pId;
	}

	public UserEntity getUser() {
		return mUser;
	}

	public void setUser(UserEntity pUser) {
		mUser = pUser;
	}

	public String getName() {
		return mName;
	}

	public void setName(String pName) {
		mName = pName;
	}

	public int getVersion() {
		return mVersion;
	}

	public void setVersion(int pVersion) {
		mVersion = pVersion;
	}

	public Date getAdded() {
		return mAdded;
	}

	public void setAdded(Date pAdded) {
		mAdded = pAdded;
	}

	public Date getLastupdate() {
		return mLastupdate;
	}

	public void setLastupdate(Date pLastupdate) {
		mLastupdate = pLastupdate;
	}

}
