package com.appliedsni.channel.core.server.user.domain;
// Generated 3 Nov, 2018 11:22:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * branchId generated by hbm2java
 */
@Embeddable
public class BranchIdEntity implements java.io.Serializable {
	@Column(name = "xcompany", nullable = false, length = 20)
	private String mCompany;
	@Column(name = "xidkey", nullable = false, length = 20)
	private String mIdKey;

	public BranchIdEntity() {
	}

	public BranchIdEntity(String mcompany, String midkey) {
		this.mCompany = mcompany;
		this.mIdKey = midkey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BranchIdEntity))
			return false;
		BranchIdEntity castOther = (BranchIdEntity) other;

		return ((this.getCompany() == castOther.getCompany()) || (this.getCompany() != null
				&& castOther.getCompany() != null && this.getCompany().equals(castOther.getCompany())))
				&& ((this.getIdKey() == castOther.getIdKey()) || (this.getIdKey() != null
						&& castOther.getIdKey() != null && this.getIdKey().equals(castOther.getIdKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompany() == null ? 0 : this.getCompany().hashCode());
		result = 37 * result + (getIdKey() == null ? 0 : this.getIdKey().hashCode());
		return result;
	}

	public String getCompany() {
		return mCompany;
	}

	public void setCompany(String pCompany) {
		mCompany = pCompany;
	}

	public String getIdKey() {
		return mIdKey;
	}

	public void setIdKey(String pIdKey) {
		mIdKey = pIdKey;
	}

}
