package com.appliedsni.channel.core.server.user.domain;
// Generated 3 Nov, 2018 11:22:10 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

/**
 * company generated by hbm2java
 */
@Entity
@Table(name = "xcompany")
public class CompanyEntity implements java.io.Serializable {
	@Id
	@Column(name = "xidkey", unique = true, nullable = false)
	@Type(type = "pg-uuid")
	private UUID mIdKey;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xaddedby")
	private UserEntity mUser;

	@Column(name = "xemail")
	private String mEmail;

	@Column(name = "xname", nullable = false)
	private String mName;

	@Column(name = "xphonenumber")
	private String mPhoneNumber;

	@Column(name = "xstatus")
	private Boolean mStatus;

	@Column(name = "xversion", nullable = false)
	private int mVersion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xadded", length = 29)
	private Date mAdded;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xlastupdate", length = 29)
	private Date mLastUpdate;

	public CompanyEntity() {
	}

	public CompanyEntity(UUID midkey, String mname, int mversion) {
		this.mIdKey = midkey;
		this.mName = mname;
		this.mVersion = mversion;
	}

	public CompanyEntity(UUID midkey, UserEntity muser, String memail, String mname, String mphonenumber,
			Boolean mstatus, int mversion, Date madded, Date mlastupdate) {
		this.mIdKey = midkey;
		this.mUser = muser;
		this.mEmail = memail;
		this.mName = mname;
		this.mPhoneNumber = mphonenumber;
		this.mStatus = mstatus;
		this.mVersion = mversion;
		this.mAdded = madded;
		this.mLastUpdate = mlastupdate;
	}

	public UUID getIdKey() {
		return mIdKey;
	}

	public void setIdKey(UUID pIdKey) {
		mIdKey = pIdKey;
	}

	public UserEntity getUser() {
		return mUser;
	}

	public void setUser(UserEntity pUser) {
		mUser = pUser;
	}

	public String getEmail() {
		return mEmail;
	}

	public void setEmail(String pEmail) {
		mEmail = pEmail;
	}

	public String getName() {
		return mName;
	}

	public void setName(String pName) {
		mName = pName;
	}

	public String getPhoneNumber() {
		return mPhoneNumber;
	}

	public void setPhoneNumber(String pPhoneNumber) {
		mPhoneNumber = pPhoneNumber;
	}

	public Boolean getStatus() {
		return mStatus;
	}

	public void setStatus(Boolean pStatus) {
		mStatus = pStatus;
	}

	public int getVersion() {
		return mVersion;
	}

	public void setVersion(int pVersion) {
		mVersion = pVersion;
	}

	public Date getAdded() {
		return mAdded;
	}

	public void setAdded(Date pAdded) {
		mAdded = pAdded;
	}

	public Date getLastUpdate() {
		return mLastUpdate;
	}

	public void setLastUpdate(Date pLastUpdate) {
		mLastUpdate = pLastUpdate;
	}

}
