package com.appliedsni.channel.core.server.user.domain;
// Generated 3 Nov, 2018 11:22:10 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

/**
 * menu generated by hbm2java
 */
@Entity
@Table(name = "xmenu"

)
public class MenuEntity implements java.io.Serializable {
	@Id
	@Column(name = "xidkey", unique = true, nullable = false)
	@Type(type = "pg-uuid")
	private UUID mIdKey;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xaddedby")
	private UserEntity mUser;

	@Column(name = "xcompany", length = 20)
	private String mCompany;

	@Column(name = "xseqno")
	private Integer mSeqno;

	@Column(name = "xmainmenu", length = 200)
	private String mMainMenu;

	@Column(name = "xsubmenu", length = 200)
	private String mSubMenu;

	@Column(name = "xdescription", length = 200)
	private String mDescription;

	@Column(name = "xurl", length = 200)
	private String mUrl;

	@Column(name = "xversion", nullable = false)
	private int mVersion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xadded", length = 29)
	private Date mAdded;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xlastupdate", length = 29)
	private Date mLastUpdate;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mMenu")
	private Set<RoleMenuEntity> mRoleMenus = new HashSet<RoleMenuEntity>(0);

	public MenuEntity() {
	}

	public MenuEntity(UUID midkey, int mversion) {
		this.mIdKey = midkey;
		this.mVersion = mversion;
	}

	public MenuEntity(UUID midkey, UserEntity muser, String mcompany, Integer mseqno, String mmainmenu, String msubmenu,
			String mdescription, String murl, int mversion, Date madded, Date mlastupdate,
			Set<RoleMenuEntity> mrolemenus) {
		this.mIdKey = midkey;
		this.mUser = muser;
		this.mCompany = mcompany;
		this.mSeqno = mseqno;
		this.mMainMenu = mmainmenu;
		this.mSubMenu = msubmenu;
		this.mDescription = mdescription;
		this.mUrl = murl;
		this.mVersion = mversion;
		this.mAdded = madded;
		this.mLastUpdate = mlastupdate;
		this.mRoleMenus = mrolemenus;
	}

	public UUID getIdKey() {
		return mIdKey;
	}

	public void setIdKey(UUID pIdKey) {
		mIdKey = pIdKey;
	}

	public UserEntity getUser() {
		return mUser;
	}

	public void setUser(UserEntity pUser) {
		mUser = pUser;
	}

	public String getCompany() {
		return mCompany;
	}

	public void setCompany(String pCompany) {
		mCompany = pCompany;
	}

	public Integer getSeqno() {
		return mSeqno;
	}

	public void setSeqno(Integer pSeqno) {
		mSeqno = pSeqno;
	}

	public String getMainMenu() {
		return mMainMenu;
	}

	public void setMainMenu(String pMainMenu) {
		mMainMenu = pMainMenu;
	}

	public String getSubMenu() {
		return mSubMenu;
	}

	public void setSubMenu(String pSubMenu) {
		mSubMenu = pSubMenu;
	}

	public String getDescription() {
		return mDescription;
	}

	public void setDescription(String pDescription) {
		mDescription = pDescription;
	}

	public String getUrl() {
		return mUrl;
	}

	public void setUrl(String pUrl) {
		mUrl = pUrl;
	}

	public int getVersion() {
		return mVersion;
	}

	public void setVersion(int pVersion) {
		mVersion = pVersion;
	}

	public Date getAdded() {
		return mAdded;
	}

	public void setAdded(Date pAdded) {
		mAdded = pAdded;
	}

	public Date getLastUpdate() {
		return mLastUpdate;
	}

	public void setLastUpdate(Date pLastUpdate) {
		mLastUpdate = pLastUpdate;
	}

	public Set<RoleMenuEntity> getRoleMenus() {
		return mRoleMenus;
	}

	public void setRoleMenus(Set<RoleMenuEntity> pRoleMenus) {
		mRoleMenus = pRoleMenus;
	}

}
