package com.appliedsni.channel.core.server.user.domain;
// Generated 3 Nov, 2018 11:22:10 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

/**
 * roleactions generated by hbm2java
 */
@Entity
@Table(name = "xroleactions")
public class RoleActionsEntity implements java.io.Serializable {
	@Id
	@Column(name = "xidkey", unique = true, nullable = false)
	@Type(type = "pg-uuid")
	private UUID mIdkey;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xentity")
	private UserEntity mEntity;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xaddedby")
	private UserEntity mUser;
	@Column(name = "xcompany", length = 20)
	private String mCompany;
	@Column(name = "xrole", length = 200)
	private String mRole;
	@Column(name = "xaction", length = 200)
	private String mAction;
	@Column(name = "xversion", nullable = false)
	private int mVersion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xadded", length = 29)
	private Date mAdded;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xlastupdate", length = 29)
	private Date mLastUpdate;

	public RoleActionsEntity() {
	}

	public RoleActionsEntity(UUID pIdkey, int pVersion) {
		this.mIdkey = pIdkey;
		this.mVersion = pVersion;
	}

	public RoleActionsEntity(UUID midkey, UserEntity mentity, UserEntity muser, String mcompany, String mrole,
			String maction, int mversion, Date madded, Date mlastupdate) {
		this.mIdkey = midkey;
		this.mEntity = mentity;
		this.mUser = muser;
		this.mCompany = mcompany;
		this.mRole = mrole;
		this.mAction = maction;
		this.mVersion = mversion;
		this.mAdded = madded;
		this.mLastUpdate = mlastupdate;
	}

	public UUID getIdkey() {
		return mIdkey;
	}

	public void setIdkey(UUID pIdkey) {
		mIdkey = pIdkey;
	}

	public UserEntity getEntity() {
		return mEntity;
	}

	public void setEntity(UserEntity pEntity) {
		mEntity = pEntity;
	}

	public UserEntity getUser() {
		return mUser;
	}

	public void setUser(UserEntity pUser) {
		mUser = pUser;
	}

	public String getCompany() {
		return mCompany;
	}

	public void setCompany(String pCompany) {
		mCompany = pCompany;
	}

	public String getRole() {
		return mRole;
	}

	public void setRole(String pRole) {
		mRole = pRole;
	}

	public String getAction() {
		return mAction;
	}

	public void setAction(String pAction) {
		mAction = pAction;
	}

	public int getVersion() {
		return mVersion;
	}

	public void setVersion(int pVersion) {
		mVersion = pVersion;
	}

	public Date getAdded() {
		return mAdded;
	}

	public void setAdded(Date pAdded) {
		mAdded = pAdded;
	}

	public Date getLastUpdate() {
		return mLastUpdate;
	}

	public void setLastUpdate(Date pLastUpdate) {
		mLastUpdate = pLastUpdate;
	}

	public String toString() {
		return this.mRole;
	}

}
