package com.appliedsni.channel.core.server.user.domain;
// Generated 3 Nov, 2018 11:22:10 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Type;

/**
 * rolemenu generated by hbm2java
 */
@Entity
@Table(name = "xrolemenu", uniqueConstraints = @UniqueConstraint(columnNames = { "xrole", "xmenu" }))
public class RoleMenuEntity implements java.io.Serializable {
	@Id
	@Column(name = "xidkey", unique = true, nullable = false)
	@Type(type = "pg-uuid")
	private UUID mIdKey;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xmenu")
	private MenuEntity mMenu;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xrole")
	private RoleEntity mRole;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xaddedby")
	private UserEntity mUser;
	@Column(name = "xcompany", length = 20)
	private String mCompany;
	@Column(name = "xversion", nullable = false)
	private int mVersion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xadded", length = 29)
	private Date mAdded;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xlastupdate", length = 29)
	private Date mLastUpdate;

	public RoleMenuEntity() {
	}

	public RoleMenuEntity(UUID midkey, int mversion) {
		this.mIdKey = midkey;
		this.mVersion = mversion;
	}

	public RoleMenuEntity(UUID midkey, MenuEntity mmenu, RoleEntity mrole, UserEntity muser, String mcompany,
			int mversion, Date madded, Date mlastupdate) {
		this.mIdKey = midkey;
		this.mMenu = mmenu;
		this.mRole = mrole;
		this.mUser = muser;
		this.mCompany = mcompany;
		this.mVersion = mversion;
		this.mAdded = madded;
		this.mLastUpdate = mlastupdate;
	}

	public UUID getIdKey() {
		return mIdKey;
	}

	public void setIdKey(UUID pIdKey) {
		mIdKey = pIdKey;
	}

	public MenuEntity getMenu() {
		return mMenu;
	}

	public void setMenu(MenuEntity pMenu) {
		mMenu = pMenu;
	}

	public RoleEntity getRole() {
		return mRole;
	}

	public void setRole(RoleEntity pRole) {
		mRole = pRole;
	}

	public UserEntity getUser() {
		return mUser;
	}

	public void setUser(UserEntity pUser) {
		mUser = pUser;
	}

	public String getCompany() {
		return mCompany;
	}

	public void setCompany(String pCompany) {
		mCompany = pCompany;
	}

	public int getVersion() {
		return mVersion;
	}

	public void setVersion(int pVersion) {
		mVersion = pVersion;
	}

	public Date getAdded() {
		return mAdded;
	}

	public void setAdded(Date pAdded) {
		mAdded = pAdded;
	}

	public Date getLastUpdate() {
		return mLastUpdate;
	}

	public void setLastUpdate(Date pLastUpdate) {
		mLastUpdate = pLastUpdate;
	}

}
