package com.appliedsni.channel.core.server.user.domain;
// Generated 3 Nov, 2018 11:22:10 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Type;

/**
 * userrole generated by hbm2java
 */
@Entity
@Table(name = "xuserrole"
		, uniqueConstraints = @UniqueConstraint(columnNames = { "xuser", "xcompany", "xbranch", "xrole" }))
public class UserRoleEntity implements java.io.Serializable {
	@Id
	@Column(name = "xidkey", unique = true, nullable = false)
	@Type(type="pg-uuid")
	private UUID mIdKey;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xrole")
	private RoleEntity mRole;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xuser")
	private UserEntity mUserByUser;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xaddedby")
	private UserEntity mUserByAddedBy;
	
	@Column(name = "xcompany", length = 20)
	private String mCompany;
	
	@Column(name = "xbranch", length = 200)
	private String mBranch;
	@Column(name = "xversion", nullable = false)
	private int mVersion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xadded", length = 29)
	private Date mAdded;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "xlastupdate", length = 29)
	private Date mLastUpdate;

	public UserRoleEntity() {
	}

	public UserRoleEntity(UUID midkey, int mversion) {
		this.mIdKey = midkey;
		this.mVersion = mversion;
	}

	public UserRoleEntity(UUID midkey, RoleEntity mrole, UserEntity muserByuser, UserEntity muserByaddedby, String mcompany,
			String mbranch, int mversion, Date madded, Date mlastupdate) {
		this.mIdKey = midkey;
		this.mRole = mrole;
		this.mUserByUser = muserByuser;
		this.mUserByAddedBy = muserByaddedby;
		this.mCompany = mcompany;
		this.mBranch = mbranch;
		this.mVersion = mversion;
		this.mAdded = madded;
		this.mLastUpdate = mlastupdate;
	}

	public UUID getIdKey() {
		return mIdKey;
	}

	public void setIdKey(UUID pIdKey) {
		mIdKey = pIdKey;
	}

	public RoleEntity getRole() {
		return mRole;
	}

	public void setRole(RoleEntity pRole) {
		mRole = pRole;
	}

	public UserEntity getUserByUser() {
		return mUserByUser;
	}

	public void setUserByUser(UserEntity pUserByUser) {
		mUserByUser = pUserByUser;
	}

	public UserEntity getUserByAddedBy() {
		return mUserByAddedBy;
	}

	public void setUserByAddedBy(UserEntity pUserByAddedBy) {
		mUserByAddedBy = pUserByAddedBy;
	}

	public String getCompany() {
		return mCompany;
	}

	public void setCompany(String pCompany) {
		mCompany = pCompany;
	}

	public String getBranch() {
		return mBranch;
	}

	public void setBranch(String pBranch) {
		mBranch = pBranch;
	}

	public int getVersion() {
		return mVersion;
	}

	public void setVersion(int pVersion) {
		mVersion = pVersion;
	}

	public Date getAdded() {
		return mAdded;
	}

	public void setAdded(Date pAdded) {
		mAdded = pAdded;
	}

	public Date getLastUpdate() {
		return mLastUpdate;
	}

	public void setLastUpdate(Date pLastUpdate) {
		mLastUpdate = pLastUpdate;
	}

	
	

}
